### ISSUE TITLE
📝 Create an Awesome list for reference architectures & compelling examples

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/CleanArchitectureV2#16]
[github.com/sindresorhus/awesome/blob/main/create-list.md](https://github.com/sindresorhus/awesome/blob/main/create-list.md)

https://github.com/SSWConsulting/awesome-clean-architecture

**Comment by danielmackay** [comment]
@Hona can we close this now?

**Comment by Hona** [comment]
Yes.
